[package]
name = "survive"
version = "0.1.0"
authors = ["Eduardo Santos <eduardosantos@tokenlab.com.br>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
